# Generated by Django 2.1.3 on 2018-11-12 17:32

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('prize', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None)),
                ('quantity', models.IntegerField(help_text='Application max quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('closed_in', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_cpf', models.CharField(max_length=11)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('winner', models.BooleanField(default=False)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raffle.Raffle')),
            ],
        ),
    ]
